name: Rust 
  
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    
    steps:
      - uses: actions/checkout@v4
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}  
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: mrtdump
          path: target/${{ matrix.BUILD_TARGET }}/mrtdump
      - name: Publish built binary to GitHub releases
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --generate-notes ./mrtdump/mrtdump#mrtdump

     