name: Rust 
  
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code       
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose  

      - name: Test
        run: cargo test --verbose